@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name createOwner
POST {{baseUrl}}/accounts/owner
Content-Type: application/json

{
	"name": "Natan Borges Owner",
	"email": "natanowner@gmail.com",
	"password": "123123"
}

###
# @name createEmployee
POST {{baseUrl}}/accounts/employee
Content-Type: application/json

{
	"name": "Natan Borges Employee",
	"email": "natanemployee@gmail.com",
	"password": "123123"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "natan@gmail.com",
	"password": "123123"
}
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Como sobreviver a vida de developer2?",
	"content": "Trabalho igual corno todo dia"
}
###

# @name fetch_recente_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
